framework:
  rate_limiter:
    email_verification:
      policy: 'fixed_window'
      limit: 1
      interval: '30 seconds'
    reset_password:
      policy: 'fixed_window'
      limit: 1
      interval: '1 hour'
